version: '2'
services:
  postgres:
      image: postgres:10.4-alpine
      volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      ports:
        - 5432:5432
      environment:
        POSTGRES_DB: db
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: password
      restart: always
  adminer:
    image: adminer
    ports:
      - 8081:8080